sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true

language: node_js
node_js:
  - "8"

install:
  - yarn

script:
  - yarn test

